#!/usr/bin/env node
// Syncs the shared shell into every page under html/.
//
//   node tools/sync-shell.mjs           rewrite out-of-date pages
//   node tools/sync-shell.mjs --check   write nothing; list out-of-date pages; exit 1 if any (also runs tools/check-shell.mjs)
//
// For each <!-- partial: NAME --> ... <!-- /partial: NAME --> pair in a page, the content between
// the markers is replaced with tools/partials/NAME.html. The marker pair "sprite" is filled from
// html/assets/icons/sprite.svg. In partials, {{root}} becomes "" for html/*.html and "../" for
// html/account/*.html (one "../" per folder of depth). A page may override that with <!-- sync-root: /kayaa/ --> (404.html only). It also sets ?v=<first 8 hex of the sha1> on every
// local .css/.js reference so browsers never serve stale files (re-run it after editing any CSS or JS).
// Everything else outside the markers is untouched.
//
// Site config: tools/site-config.json is the single source for shipping_fee, free_shipping_over, pay_button_label,
// order_emails_enabled, remember_days and low_stock_threshold. This script
//   - refreshes the text of every <tag data-cfg="KEY">text</tag> (money keys print as "Rs. 7,500") and sets the attributes
//     named in data-cfg-attr="attribute:KEY attribute:KEY" (raw values), so --check flags stale text and nothing needs a hand edit;
//   - writes html/assets/js/site-config.js (window.KAYAA_CONFIG) for the scripts. Blade replaces both with view variables.
// Dev-only: this folder is never published. Plain Node, no dependencies.

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { checkShell } from './check-shell.mjs';
import { loadCatalogue, generate, catalogueJs, checkCoverage } from './catalogue.mjs';
import { loadContent, loadIntros } from './content.mjs';
import { loadSeo, seoBlock, metaOf } from './seo.mjs';

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const htmlDir = path.join(repo, 'html');
const partialsDir = path.join(repo, 'tools', 'partials');
const spritePath = path.join(htmlDir, 'assets', 'icons', 'sprite.svg');
const check = process.argv.includes('--check');
// <body data-footer-from="white|secondary"> per page, recorded in tools/shell-map.json ("footerFrom"): the colour the footer's gradient starts from,
// so it joins a last section that sits on a different full-bleed colour. Written here; tools/check-footer-seam.mjs measures the seam.
const shellMap = JSON.parse(fs.readFileSync(new URL('./shell-map.json', import.meta.url), 'utf8'));

// ---- site config ----
const config = JSON.parse(fs.readFileSync(path.join(repo, 'tools', 'site-config.json'), 'utf8'));
const MONEY_KEYS = new Set(['shipping_fee', 'free_shipping_over']);   // printed with the currency prefix: "Rs. 7,500"
const cfgText = (key) => (MONEY_KEYS.has(key) ? `${config.currency_prefix} ${Number(config[key]).toLocaleString('en-US')}` : String(config[key]));
const escHtml = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
// ---- catalogue (tools/catalogue.json), content pack (docs/content) and SEO (tools/seo.json) ----
const catalogue = loadCatalogue(repo);
checkCoverage(catalogue).forEach((p) => { console.error('error: catalogue: ' + p); process.exitCode = 1; });
const content = loadContent(repo);
const seo = loadSeo(repo);
const baseCtx = { repo, cfg: config, cfgText, content, cat: catalogue };
const intros = loadIntros(repo, { ...baseCtx, root: '' });
baseCtx.intros = intros;
const seoCtx = { ...baseCtx, seo, intros };
generate('size-rows', '', { ...baseCtx, root: '' });   // fail early on a broken catalogue or size chart
const seoPublic = { staging: seo.staging !== false, siteUrl: seo.site.url, pages: { shop: metaOf('shop.html', seoCtx), search: metaOf('search.html', seoCtx) } };
const configJs = `/* Generated by tools/sync-shell.mjs from tools/site-config.json and tools/seo.json. Do not edit by hand.
   Blade replaces this file with an inline script that prints the real config (window.KAYAA_CONFIG) and the SEO switch (window.KAYAA_SEO). */
window.KAYAA_CONFIG = ${JSON.stringify(config, null, 2)};
window.KAYAA_SEO = ${JSON.stringify(seoPublic, null, 2)};
`;
const generatedFiles = [
  [path.join(htmlDir, 'assets', 'js', 'site-config.js'), configJs],
  [path.join(htmlDir, 'assets', 'js', 'catalogue-data.js'), catalogueJs(catalogue, intros)]
];
const staleGenerated = generatedFiles.filter(([f, body]) => !fs.existsSync(f) || fs.readFileSync(f, 'utf8') !== body);
if (!check) staleGenerated.forEach(([f, body]) => fs.writeFileSync(f, body));
const GEN_RE = /([ \t]*)<!-- gen: ([\w-]+)([^>]*?) -->([\s\S]*?)<!-- \/gen: \2 -->/g;
const PHOTO_RE = /<!-- photo: ([\w-]+) -->([\s\S]*?)<!-- \/photo: \1 -->/g;

const CFG_TEXT_RE = /(<([a-z][a-z0-9]*)\b[^>]*\bdata-cfg="(\w+)"[^>]*>)([^<]*)(<\/\2>)/g;
const CFG_ATTR_RE = /<[a-z][a-z0-9]*\b[^>]*\bdata-cfg-attr="([^"]+)"[^>]*>/g;

const hashes = new Map();
const hash = (abs) => {
  if (!hashes.has(abs)) hashes.set(abs, crypto.createHash('sha1').update(fs.readFileSync(abs)).digest('hex').slice(0, 8));
  return hashes.get(abs);
};

const toLF =(s) => s.replace(/\r\n/g, '\n');

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) return walk(p);
    return e.isFile() && e.name.endsWith('.html') ? [p] : [];
  });
}

function loadPartial(name) {
  if (name === 'sprite') {
    // Same wrapper the pages have always used; indented to sit inside <body>.
    const svg = toLF(fs.readFileSync(spritePath, 'utf8')).trim().replace(/^<svg /, '<svg aria-hidden="true" ');
    return svg.split('\n').map((l) => (l ? '  ' + l : l)).join('\n');
  }
  const file = path.join(partialsDir, `${name}.html`);
  if (!fs.existsSync(file)) return null;
  return toLF(fs.readFileSync(file, 'utf8')).replace(/^\n+|\s+$/g, '');
}

const cache = new Map();
const partial = (name) => {
  if (!cache.has(name)) cache.set(name, loadPartial(name));
  return cache.get(name);
};

const stale = [];
const problems = [];
let pages = 0;

for (const file of walk(htmlDir).sort()) {
  pages++;
  const rel = path.relative(htmlDir, file).split(path.sep);
  let root = '../'.repeat(rel.length - 1);
  const label = rel.join('/');
  const original = fs.readFileSync(file, 'utf8');
  const eol = original.includes('\r\n') ? '\r\n' : '\n';
  let text = toLF(original);
  // Per-file override: <!-- sync-root: /kayaa/ --> makes {{root}} resolve to that prefix (used only by 404.html, because
  // GitHub Pages serves it at the missing URL's path, so relative links would break). Local .css/.js are found under html/.
  const override = text.match(/<!-- sync-root: (\S+) -->/);
  if (override) root = override[1];

  const names = [...text.matchAll(/<!-- partial: ([\w-]+) -->/g)].map((m) => m[1]);
  for (const name of new Set(names)) {
    const body = name === 'seo' ? seoBlock(label, text, seoCtx) : partial(name);
    if (body === null) {
      problems.push(`${label}: no partial file for "${name}"`);
      continue;
    }
    const re = new RegExp(`([ \\t]*)<!-- partial: ${name} -->[\\s\\S]*?<!-- /partial: ${name} -->`);
    if (!new RegExp(`<!-- /partial: ${name} -->`).test(text)) {
      problems.push(`${label}: "${name}" has no closing marker`);
      continue;
    }
    text = text.replace(re, (_, indent) => {
      const inner = body.replace(/\{\{root\}\}/g, root);
      return `${indent}<!-- partial: ${name} -->\n${inner}\n${indent}<!-- /partial: ${name} -->`;
    });
  }

  // Catalogue regions: <!-- gen: NAME args --> ... <!-- /gen: NAME --> (photo markers inside keep what process-images wrote)
  text = text.replace(GEN_RE, (m, indent, name, args, old) => {
    const keep = {};
    for (const p of old.matchAll(PHOTO_RE)) keep[p[1]] = p[2];
    const body = generate(name, args.trim(), { ...baseCtx, root });
    let lines = body.split('\n').map((l) => (l ? indent + l : l)).join('\n');
    // the old content between photo markers is kept as it is (it already carries its indentation)
    lines = lines.replace(PHOTO_RE, (pm, id, inner) => '<!-- photo: ' + id + ' -->' + (id in keep ? keep[id] : inner) + '<!-- /photo: ' + id + ' -->');
    return `${indent}<!-- gen: ${name}${args} -->\n${lines}\n${indent}<!-- /gen: ${name} -->`;
  });

  // Config hooks: [data-cfg] text and data-cfg-attr attributes.
  text = text.replace(CFG_TEXT_RE, (m, open, tag, key, old, close) => {
    if (!(key in config)) { problems.push(`${label}: unknown data-cfg key "${key}"`); return m; }
    return open + escHtml(cfgText(key)) + close;
  });
  text = text.replace(CFG_ATTR_RE, (tag, pairs) => {
    for (const pair of pairs.trim().split(/\s+/)) {
      const [attr, key] = pair.split(':');
      if (!(key in config)) { problems.push(`${label}: unknown data-cfg-attr key "${key}"`); continue; }
      const val = escHtml(String(config[key])).replace(/"/g, '&quot;');
      const re = new RegExp('(\\s' + attr + '=")[^"]*(")');
      tag = re.test(tag) ? tag.replace(re, (_, a, b) => a + val + b) : tag.replace(/\s*\/?>$/, (end) => ` ${attr}="${val}"` + end);
    }
    return tag;
  });

  // footer seam: data-footer-from on <body>
  {
    const from = (shellMap.footerFrom || {})[label];
    text = text.replace(/<body\b([^>]*)>/, (m, attrs) => {
      const rest = attrs.replace(/\s+data-footer-from="[^"]*"/, '');
      return `<body${rest}${from ? ` data-footer-from="${from}"` : ''}>`;
    });
  }

  // Cache busting: every local .css/.js reference gets ?v=<first 8 hex of the file's sha1>.
  text = text.replace(/\b(href|src)="((?!https?:|\/\/|#|mailto:|tel:|data:)[^"?#]+\.(?:css|js))(?:\?v=[0-9a-f]*)?"/g, (m, attr, url) => {
    const abs = override && url.startsWith(root) ? path.join(htmlDir, url.slice(root.length)) : path.resolve(path.dirname(file), url);
    if (!fs.existsSync(abs)) { problems.push(`${label}: missing file ${url}`); return m; }
    return `${attr}="${url}?v=${hash(abs)}"`;
  });

  const next = text.replace(/\n/g, eol);
  if (next !== original) {
    stale.push(label);
    if (!check) fs.writeFileSync(file, next);
  }
  // Pages copied from the skeleton must have {{root}} resolved by hand outside the markers.
  if (/\{\{root\}\}/.test(text)) problems.push(`${label}: unresolved {{root}} outside a partial`);
}

// every page renders the shell its variant allows (tools/shell-map.json)
const shellProblems = checkShell(repo);
shellProblems.forEach((p) => console.error('ERROR shell: ' + p));
if (shellProblems.length) process.exitCode = 1;

problems.forEach((p) => console.error('warning: ' + p));
staleGenerated.forEach(([f]) => { stale.push(path.relative(htmlDir, f).split(path.sep).join('/') + ' (generated)'); pages++; });

if (check) {
  stale.forEach((f) => console.log('out of date: html/' + f));
  console.log(`${stale.length} of ${pages} pages out of date`);
  process.exit(stale.length || shellProblems.length || problems.some((p) => !p.includes('outside')) ? 1 : 0);
}
console.log(`${stale.length} of ${pages} pages updated`);
