#!/usr/bin/env node
// Syncs the shared shell into every page under html/.
//
//   node tools/sync-shell.mjs           rewrite out-of-date pages
//   node tools/sync-shell.mjs --check   write nothing; list out-of-date pages; exit 1 if any
//
// For each <!-- partial: NAME --> ... <!-- /partial: NAME --> pair in a page, the content between
// the markers is replaced with tools/partials/NAME.html. The marker pair "sprite" is filled from
// html/assets/icons/sprite.svg. In partials, {{root}} becomes "" for html/*.html and "../" for
// html/account/*.html (one "../" per folder of depth). A page may override that with <!-- sync-root: /kayaa/ --> (404.html only). It also sets ?v=<first 8 hex of the sha1> on every
// local .css/.js reference so browsers never serve stale files (re-run it after editing any CSS or JS).
// Everything else outside the markers is untouched.
//
// Site config: tools/site-config.json is the single source for shipping_fee, free_shipping_over, pay_button_label,
// order_emails_enabled, remember_days and low_stock_threshold. This script
//   - refreshes the text of every <tag data-cfg="KEY">text</tag> (money keys print as "Rs 7,500") and sets the attributes
//     named in data-cfg-attr="attribute:KEY attribute:KEY" (raw values), so --check flags stale text and nothing needs a hand edit;
//   - writes html/assets/js/site-config.js (window.KAYAA_CONFIG) for the scripts. Blade replaces both with view variables.
// Dev-only: this folder is never published. Plain Node, no dependencies.

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const htmlDir = path.join(repo, 'html');
const partialsDir = path.join(repo, 'tools', 'partials');
const spritePath = path.join(htmlDir, 'assets', 'icons', 'sprite.svg');
const check = process.argv.includes('--check');

// ---- site config ----
const config = JSON.parse(fs.readFileSync(path.join(repo, 'tools', 'site-config.json'), 'utf8'));
const MONEY_KEYS = new Set(['shipping_fee', 'free_shipping_over']);
const cfgText = (key) => (MONEY_KEYS.has(key) ? 'Rs ' + Number(config[key]).toLocaleString('en-US') : String(config[key]));
const escHtml = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const configJs = `/* Generated by tools/sync-shell.mjs from tools/site-config.json. Do not edit by hand.
   Blade replaces this file with an inline script that prints the real config (window.KAYAA_CONFIG). */
window.KAYAA_CONFIG = ${JSON.stringify(config, null, 2)};
`;
const configJsPath = path.join(htmlDir, 'assets', 'js', 'site-config.js');
const configStale = !fs.existsSync(configJsPath) || fs.readFileSync(configJsPath, 'utf8') !== configJs;
if (configStale && !check) fs.writeFileSync(configJsPath, configJs);

const CFG_TEXT_RE = /(<([a-z][a-z0-9]*)\b[^>]*\bdata-cfg="(\w+)"[^>]*>)([^<]*)(<\/\2>)/g;
const CFG_ATTR_RE = /<[a-z][a-z0-9]*\b[^>]*\bdata-cfg-attr="([^"]+)"[^>]*>/g;

const hashes = new Map();
const hash = (abs) => {
  if (!hashes.has(abs)) hashes.set(abs, crypto.createHash('sha1').update(fs.readFileSync(abs)).digest('hex').slice(0, 8));
  return hashes.get(abs);
};

const toLF =(s) => s.replace(/\r\n/g, '\n');

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) return walk(p);
    return e.isFile() && e.name.endsWith('.html') ? [p] : [];
  });
}

function loadPartial(name) {
  if (name === 'sprite') {
    // Same wrapper the pages have always used; indented to sit inside <body>.
    const svg = toLF(fs.readFileSync(spritePath, 'utf8')).trim().replace(/^<svg /, '<svg aria-hidden="true" ');
    return svg.split('\n').map((l) => (l ? '  ' + l : l)).join('\n');
  }
  const file = path.join(partialsDir, `${name}.html`);
  if (!fs.existsSync(file)) return null;
  return toLF(fs.readFileSync(file, 'utf8')).replace(/^\n+|\s+$/g, '');
}

const cache = new Map();
const partial = (name) => {
  if (!cache.has(name)) cache.set(name, loadPartial(name));
  return cache.get(name);
};

const stale = [];
const problems = [];
let pages = 0;

for (const file of walk(htmlDir).sort()) {
  pages++;
  const rel = path.relative(htmlDir, file).split(path.sep);
  let root = '../'.repeat(rel.length - 1);
  const label = rel.join('/');
  const original = fs.readFileSync(file, 'utf8');
  const eol = original.includes('\r\n') ? '\r\n' : '\n';
  let text = toLF(original);
  // Per-file override: <!-- sync-root: /kayaa/ --> makes {{root}} resolve to that prefix (used only by 404.html, because
  // GitHub Pages serves it at the missing URL's path, so relative links would break). Local .css/.js are found under html/.
  const override = text.match(/<!-- sync-root: (\S+) -->/);
  if (override) root = override[1];

  const names = [...text.matchAll(/<!-- partial: ([\w-]+) -->/g)].map((m) => m[1]);
  for (const name of new Set(names)) {
    const body = partial(name);
    if (body === null) {
      problems.push(`${label}: no partial file for "${name}"`);
      continue;
    }
    const re = new RegExp(`([ \\t]*)<!-- partial: ${name} -->[\\s\\S]*?<!-- /partial: ${name} -->`);
    if (!new RegExp(`<!-- /partial: ${name} -->`).test(text)) {
      problems.push(`${label}: "${name}" has no closing marker`);
      continue;
    }
    text = text.replace(re, (_, indent) => {
      const inner = body.replace(/\{\{root\}\}/g, root);
      return `${indent}<!-- partial: ${name} -->\n${inner}\n${indent}<!-- /partial: ${name} -->`;
    });
  }

  // Config hooks: [data-cfg] text and data-cfg-attr attributes.
  text = text.replace(CFG_TEXT_RE, (m, open, tag, key, old, close) => {
    if (!(key in config)) { problems.push(`${label}: unknown data-cfg key "${key}"`); return m; }
    return open + escHtml(cfgText(key)) + close;
  });
  text = text.replace(CFG_ATTR_RE, (tag, pairs) => {
    for (const pair of pairs.trim().split(/\s+/)) {
      const [attr, key] = pair.split(':');
      if (!(key in config)) { problems.push(`${label}: unknown data-cfg-attr key "${key}"`); continue; }
      const val = escHtml(String(config[key])).replace(/"/g, '&quot;');
      const re = new RegExp('(\\s' + attr + '=")[^"]*(")');
      tag = re.test(tag) ? tag.replace(re, (_, a, b) => a + val + b) : tag.replace(/\s*\/?>$/, (end) => ` ${attr}="${val}"` + end);
    }
    return tag;
  });

  // Cache busting: every local .css/.js reference gets ?v=<first 8 hex of the file's sha1>.
  text = text.replace(/\b(href|src)="((?!https?:|\/\/|#|mailto:|tel:|data:)[^"?#]+\.(?:css|js))(?:\?v=[0-9a-f]*)?"/g, (m, attr, url) => {
    const abs = override && url.startsWith(root) ? path.join(htmlDir, url.slice(root.length)) : path.resolve(path.dirname(file), url);
    if (!fs.existsSync(abs)) { problems.push(`${label}: missing file ${url}`); return m; }
    return `${attr}="${url}?v=${hash(abs)}"`;
  });

  const next = text.replace(/\n/g, eol);
  if (next !== original) {
    stale.push(label);
    if (!check) fs.writeFileSync(file, next);
  }
  // Pages copied from the skeleton must have {{root}} resolved by hand outside the markers.
  if (/\{\{root\}\}/.test(text)) problems.push(`${label}: unresolved {{root}} outside a partial`);
}

problems.forEach((p) => console.error('warning: ' + p));
if (configStale) { stale.push('assets/js/site-config.js'); pages++; }

if (check) {
  stale.forEach((f) => console.log('out of date: html/' + f));
  console.log(`${stale.length} of ${pages} pages out of date`);
  process.exit(stale.length || problems.some((p) => !p.includes('outside')) ? 1 : 0);
}
console.log(`${stale.length} of ${pages} pages updated`);
